name: Python CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
    # Step 1: Checkout the code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.9

    # Step 3: Install dependencies
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Run tests
    - name: Run Tests
      run: |
        pytest tests/

  lint:
    runs-on: ubuntu-22.04

    steps:
    # Step 1: Checkout the code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.9

    # Step 3: Install linters
    - name: Install Linters
      run: |
        pip install flake8 black

    # Step 4: Run linters
    - name: Run Flake8
      run: |
        flake8 . \
          --max-line-length=88 \
          --extend-ignore=E501 \
          --ignore=D203,D205,D400
    - name: Run Black (Check Only)
      run: black --check .
  
  security:
    runs-on: ubuntu-22.04

    steps:
    # Step 1: Checkout the code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.9
    
    # Step 3: Install Security Tools
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Run Security Tools
    - name: Dependency Vulnerability Scan
      run: pip-audit

    - name: Code Security Scan (Bandit)
      run: bandit -r .

    - name: Secret Detection (TruffleHog)
      run: trufflehog filesystem .
